#define kDMRoutesandStopsUrl @"http://shuttles.rpi.edu/displays/netlink.js"
#define kDMShuttlesUrl @"http://shuttles.abstractedsheep.com/data_service.php?action=get_shuttle_positions"
#define kDMAllEtasUrl @"http://shuttles.abstractedsheep.com/data_service.php?action=get_all_eta"
#define kDMNextEtasUrl @"http://shuttles.abstractedsheep.com/data_service.php?action=get_next_eta"
#define kLEExtraEtasUrl @"http://shuttles.abstractedsheep.com/data_service.php?action=get_all_extra_eta"
